name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ['*.md']
    branches: ['main', 'master', 'update/040']
  push:
    paths-ignore: ['*.md']
    branches: ['main', 'master', 'update/040']

jobs:
  BuildPackage:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Prepare StartOS SDK
        uses: k0gen/sdk@v3-optimization

      - name: Set up QEMU for AMD64 emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64
          cache-image: true

      - name: Checkout services repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the service package
        id: build
        run: |
          start-cli init
          RUST_LOG=debug RUST_BACKTRACE=1 make
          PACKAGE_ID=$(start-cli s9pk inspect *.s9pk manifest | jq -r '.id')
          echo "package_id=${PACKAGE_ID}" >> $GITHUB_ENV
          printf "\n SHA256SUM: $(sha256sum ${PACKAGE_ID}.s9pk) \n"
        shell: bash

      - name: Upload .s9pk
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.package_id }}.s9pk
          path: ./${{ env.package_id }}.s9pk
